"""added added_by field

Revision ID: f32c1dbf66c4
Revises: 
Create Date: 2024-01-04 11:36:58.166672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32c1dbf66c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('added_by', sa.String(length=64), nullable=True))
    op.alter_column('url_map', 'short',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.create_unique_constraint(None, 'url_map', ['short'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_map', type_='unique')
    op.alter_column('url_map', 'short',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.drop_column('url_map', 'added_by')
    # ### end Alembic commands ###
